---
some_fact: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66643339323935383337376230306461653966623035393864346233353630333139363532326538
          6465346130366239383731313830633938326532643161320a653362323338393736356136346538
          37356531393933376139613564376334313063376665383964613666336261656237366634306433
          6263363133376236330a323336643930356132333634336139333636336330616136646563383663
          6164
